### ISSUE TITLE
🐛 Settings Is Duplicated Instead Of Focused

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#104]
### Bug Description

When accessing the settings menu from the loop Menu Bar extension, a new Settings Menu is created, even if there is already an open Settings Menu. This should not happen. Instead, clicking on the settings button from the Menu Bar extension should focus any existing Settings Menus.

### Steps To Reproduce

1. Open Loop Menu Bar menu.
2. Click ⌘,
3. Repeat

### Expected Behavior

Clicking on the Settings button from the Menu Bar extension should focus any existing Settings Menus.

### Actual Behavior

Clicking on the Settings button from the Menu Bar extension creates a new Settings Menu, regardless if one is open already.

### Screenshots

https://github.com/MrKai77/Loop/assets/60551230/be265c9e-071a-4eb9-8159-49c3d8f5b450

### MacOS Version

14.1.1 (23B81)

### Loop Version

1.0.0-beta.12 (515)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
I can reproduce that bug here. This seems to be a problem with the [Settings](https://github.com/sindresorhus/Settings/issues?q=swiftui) package I use for Loop. Before this, there was also #80, and now there's this issue and also #92, which are all issues with the settings package.
Looks like the best option here might be to just make my own settings window using SwiftUI, since I already know that that will fix both this and the other issue.

**Comment by MrKai77** [comment]
Alright, there's the latest build with this issue fixed!
[Loop.zip](https://github.com/MrKai77/Loop/files/13519392/Loop.zip)

**Comment by MrKai77** [comment]
Actually, here's the latest build 😅:
[Loop.zip](https://github.com/MrKai77/Loop/files/13519554/Loop.zip)

**Comment by JaceThings** [comment]
Works :)
