### ISSUE TITLE
✨ Add link to github repo in settings window

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#113]
### Feature Request Description

1.) Add link to github repo in the more section

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Alright, after experimenting for a bit, I decided that having a "Send Feedback" button was better than having a GitHub link, since otherwise, the formatting looked a little odd. Also, you can already access the GitHub from the Loop's About window :)

Here's the latest build:
[Loop.zip](https://github.com/MrKai77/Loop/files/13763067/Loop.zip)

Screenshot:
<img width="562" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/d160d6ab-247d-4ec9-8ee1-90c185043f61">
