### ISSUE TITLE
🐛 Holding second direction key then letting go of first one doesn't change window action

### ISSUE THREAD

**Issue by The-Ducktor** [MrKai77/Loop#177]
### Bug Description

When you activate the loop by pressing the designated key (in my case, the fn key), using the arrow keys to navigate from side to side works perfectly. However, if you hold down a key, such as the left arrow, while simultaneously touching the right arrow and then release it, nothing happens it keeps the original direction

### Steps To Reproduce

1. Open app / setup i guess
2. press modifier key
3. use arrow key then while still holding down a key press an opposite key

### Expected Behavior

it when letting go of the orignal key it should go to the direction of the new one that is being pressed down

### Actual Behavior

it just keeps the circle in the direction of the original key

### MacOS Version

14.2.1 (23C71)

### Loop Version

1.0.0-beta.13

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Interesting! I'll look into this!

**Comment by MrKai77** [comment]
Alright, after rethinking this, it will not be possible to fix. This is because when closing Loop *after* having chosen an action, the user needs to release both keys. 

If this were implemented, that means that the first key that is released would change the action back to another action, which would not be the desired behavior.

For example:
1. The user triggers Loop and presses <kbd>a</kbd> + <kbd>w</kbd> for top left corner
2. They release both <kbd>a</kbd> + <kbd>w</kbd> and the trigger key, however, not all keys will be released at the same time. For example:
    1. They release <kbd>a</kbd> first; This changes the action to top half
    2. they release <kbd>w</kbd>; This may change it to no action
    3. They release the trigger key

While I could use timers between key releases, this would lead to a "laggy" behavior, that doesn't quite feel right either.
