### ISSUE TITLE
✨ Nightlies/commit builds

### ISSUE THREAD

**Issue by jacksongoode** [MrKai77/Loop#182]
### Feature Request Description

It could be cool if the nightlies were built on every push for development testing, so folks can give more iterative feedback to you. This might not be a priority if you expect to release quickly.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yeah this has been something I've been wanting to do for a while as well. I actually used to have them set up with GitHub Actions, but since Loop now requires Xcode 15, I've been waiting for GitHub to update their own runners (since they currently run on Xcode 14). 

Another reason to resolve this would be to finally make the `Include development versions` toggle button actually do something haha..

Anyways, back when I used GitHub Actions, I also couldn't get Loop codesigned properly and it wouldn't launch on my computer, so that will require some investigation too :)

**Comment by MrKai77** [comment]
Update: I was looking through 
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md

and found Xcode 15 on the list, so I guess I haven't checked in a while.
So all that's required now should be to update the GitHub actions workflow file!

**Comment by JaceThings** [comment]
I would be interested in this! I check this repo like three times a day to look for a .zip file in a random ticket 😅

**Comment by MrKai77** [comment]
Status update: Got the GitHub Actions Loop build (which runs on every commit on the `develop` branch) working! But version numbers seem to be non-functional yet...
<img width="328" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/426503a1-99cc-48d8-be64-bc102ce4eedf">
