### ISSUE TITLE
✨ Don't truncate numbers in number input

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#207]
### Feature Request Description

Long values in the number counter get cut off. I don't think this should happen.

### Screenshots

![004380@2x](https://github.com/MrKai77/Loop/assets/60551230/ff575d58-0c8a-4baf-9c51-c5e55a4cb10b)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Yup, I actually did a lot of research on working around this SwiftUI limitation but to no avail :(

I believe that the best solution would be to make my own custom "Textbox with stepper" view, and then use that across all of Loop's settings. I might also be able to integrate a slider onto this reusable view, so that everyone can get varying levels of *exact* customizability if needed.

**Comment by MrKai77** [comment]
It is finally done! Here's a quick preview clip:
https://github.com/MrKai77/Loop/assets/68963405/b63aa93f-7f55-473b-a0e5-c295b2bfeaec

As well as a build:
[Loop.zip](https://github.com/MrKai77/Loop/files/14305628/Loop.zip)

Let me know if there's anything to be improved!
