### ISSUE TITLE
✨ Custom Position Values

### ISSUE THREAD

**Issue by JaceThings** [MrKai77/Loop#225]
### Feature Request Description

It would be great to position windows arbitrarily rather than just left, right, or top (corners too).

What if I just wanted a window to be slightly offset to the right?

### Screenshots

![004834@2x](https://github.com/MrKai77/Loop/assets/60551230/5571182c-0719-4bfd-bffd-f935e0bc1a45)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Interesting, I never saw the need in this so I never ended up implementing it haha
So if the user has pixels set as their measurement unit, they would be able to offset the window frame by pixels, and if it's set to percentages, the user could offset the window frame by a percentage relative to the current screen?

**Comment by JaceThings** [comment]
That could work. Rectangle uses coordinates that you just have to calculate, based on the resolution of your display.
![004962@2x](https://github.com/MrKai77/Loop/assets/60551230/41996837-fa8d-4a4c-b552-0e246a5b1724)

I do like offsets more personally, but hey, if a user knows coordinates, they probably would want to use them.

**Comment by Anatharias** [comment]
I second this. 
I created pre-set areas on my Ultrawide
36% | 36% | 28%
alas, only the left and right positions are respected, since they touch the sides of the display.
The middle 36% is getting its anchor from the middle of the screen, and no option allows setting its centering at 54% (36% + 36/2%).

Thanks

**Comment by MrKai77** [comment]
Here's a working build: [Loop.zip](https://github.com/MrKai77/Loop/files/14729338/Loop.zip)
Screenshot:
![image](https://github.com/MrKai77/Loop/assets/68963405/087c76de-ace9-47ac-b970-2cefc0b34eb2)
Let me know if you find any bugs :D
Otherwise, I'll be merging this really soon so that it's included in the next release!

**Comment by JaceThings** [comment]
hehehe, this is so cool, gonna test

**Comment by JaceThings** [comment]
All of the "custom" cycles are broken 💀

Video:
https://li.mt/81kRYxZ5

Import:
[keybinds.json](https://github.com/MrKai77/Loop/files/14729416/keybinds.json)

**Comment by JaceThings** [comment]
To be more clear, every single custom layout has to be turned into a percentage and then back to pixels and then have their values reset from the beginning.

Video:
https://li.mt/lJg7TS7m

**Comment by MrKai77** [comment]
Alright, looks like I was too focused on that specific feature that I forgot to test cycling 💀
Will definitely try and fix this asap!

**Comment by JaceThings** [comment]
macOS centre / default centre also does not work, even though it it not a custom one 😭

**Comment by MrKai77** [comment]
Here's a fixed build!
~[Loop.zip](https://github.com/MrKai77/Loop/files/14729879/Loop.zip)~

> To be more clear, every single custom layout has to be turned into a percentage and then back to pixels and then have their values reset from the beginning.

Currently, this is done so that I can use the same method for both the preview window and the actual resizing of the window. But if I can come up with something more efficient, I will definitely do that!

EDIT: just realized that this breaks Loop's compatibility with Stage Manager. Will rewrite the function to return everything in pixels instead of percentages 😅

**Comment by MrKai77** [comment]
Alright, here's a new build:
[Loop.zip](https://github.com/MrKai77/Loop/files/14765457/Loop.zip)

This time, I tried to test it extensively so I hope that it is close to (if not) bugless :D

**Comment by JaceThings** [comment]
W update, all fixed
