### ISSUE TITLE
✨ Moving and resizing functionalities

### ISSUE THREAD

**Issue by Dhairy2003** [MrKai77/Loop#239]
### Feature Request Description

The user will need to hold down a key/keys and then use the mouse to move/resize windows. 

### Screenshots

https://github.com/MrKai77/Loop/assets/101127874/086d52c5-0c5d-44aa-9dec-7452576465b2

### Additional Context

Custom keybinds to move a window can also be introduced using the same modifier key/keys.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by frieza213** [comment]
very cool idea but i don't think it will be any more productive than the usual click and drag or 3 finger drag(middle click drag) in my opinion(i only mean this about the moving part the resizing part looks really interesting though)

**Comment by Dhairy2003** [comment]
@AISLVE I use a mouse and i find it  annoying to reach the title bar everytime i want to move a window  , specially in situations like this
![image](https://github.com/MrKai77/Loop/assets/101127874/738df3df-c318-4fd6-bf0d-08affe8e82cd)

**Comment by MrKai77** [comment]
Unfortunately, I don't see the appeal of implementing this into Loop.

Loop was made to help organize windows using preset window frames, so that the user can't be bothered to move *and* resize each window individually. With Loop, they could simply press a key, and do both at once, while also following the window padding and edges of other windows. 

However, if you'd really like to use this feature, other apps such as https://github.com/pablopunk/SwiftShift provides this functionality. Loop will likely work perfectly together for you with this :)
