### ISSUE TITLE
✨ Fullscreen apps above the notch

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#245]
### Feature Request Description

Hey can you implement this in your app i think this will be very nice when you want even that little space for when you are reading, watching a movie or things like that [Article link](https://notes.alinpanaitiu.com/Fullscreen-apps-above-the-MacBook-notch)
* **Make sure to check out the sip disable paragraph**

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by frieza213** [comment]
![IMAGE 2024-03-08 22:01:08](https://github.com/MrKai77/Loop/assets/121119257/92304ac5-3675-473f-b809-357a281df271)

**Comment by MrKai77** [comment]
Unfortunately, this seems to involve modifying other apps' code, which is something I don't want to deal with (since this will most likely only work with a limited number of apps). However, you can also do this manually through an app's info window as shown below:
<img width="504" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/df371555-fe51-484b-ab7c-9f600ec3887c">

Apple has more details [here](https://support.apple.com/en-ca/102125#:~:text=Turn%20on%20'Scale%20to%20fit,in%20camera'%20for%20an%20app&text=Click%20the%20Finder%20icon%20in,below%20built%2Din%20camera.%22) :)

(Please let me know if I misunderstood)

**Comment by frieza213** [comment]
But this would not allow the fullscreen with notch like shown in the photo I provided( you can see the app ignores the notch and is behind it too instead of leaving the weird space in fullscreen)
It is hard to explain but this option doesn't do what I have shown in the picture read the article there you can see what I meant, like above the notch the windows fullscreen like I know this is hard to explain

**Comment by MrKai77** [comment]
I think I understand now. You want to be able to show the notch when an app is in fullscreen.
But as I said before, I don't want to be modifying other apps from Loop, as it could be unreliable, and may not work with all apps.

For example, in the section "SIP disabled? How about no?", they state that it is not possible to modify system apps. Furthermore, near the end of the article, they explain, "I also tried testing this on VirtualBuddy but because it has a required entitlement (`com.apple.vm.networking`) and an embedded provisioning profile tied to the developer certificate, this got too complicated to warrant the effort," showing that again, this will not work with all apps.

(Also next time, please just @ me in this issue, instead of posting a comment in an unrelated issue telling me to read this one)

**Comment by frieza213** [comment]
yeah but it would be nice to have it for the apps working but still i respect your decision so ok🤝

**Comment by frieza213** [comment]
oh i thought you don't get notified for closed issues my bad
