### ISSUE TITLE
🐛 Loop doesn't work with Firefox

### ISSUE THREAD

**Issue by minisiowo** [MrKai77/Loop#249]
### Bug Description

The first attempt to resize the Firefox (Firefox Dev Edition Too) browser window causes the window to change, but not in the expected way. Initially, the window changes its size randomly, on the second attempt, the window moves to the designated place, and only on the third attempt does the window change its size to the expected one.

### Steps To Reproduce

1. Open the Loop application on MacOS.
2. Attempt to resize a window using the Loop app's radial menu.
3. Observe the window's behavior during the first, second, and third attempts at resizing.

### Expected Behavior

It was expected that the window would resize smoothly and directly to the selected dimensions on the first attempt using the Loop application's features.

### Actual Behavior

During the first attempt to resize through the Loop application, the window's dimensions change randomly. During the second attempt, the window moves to a designated place. Only on the third attempt does the window resize to the expected dimensions.

### Screenshots

![firefox_loop_issue](https://github.com/MrKai77/Loop/assets/109168517/43d0faa3-5998-4799-9c2c-84b614508f5b)

### MacOS Version

14.4 (23E214)

### Loop Version

Version 1.0.0-beta.14 (644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by JaceThings** [comment]
I can also vouch for the same issue as mentioned with Notion months ago.

**Comment by MrKai77** [comment]
Oh yeah I just tested it and can reproduce it on my side as well. 
It's really weird because other apps such as Raycast and Rectangle seem to be having no problem resizing Firefox's window.
I will inspect Rectangle's source code to see what Loop could be doing differently :)

(and hopefully this will also resolve #146)

**Comment by MrKai77** [comment]
I spent a few hours trying to figure this out only to notice that Loop didn't support any apps with the accessibility attribute `AXEnhancedUserInterface` enabled! Now, Loop will temporarily disable it when resizing a window, similarly to how Rectangle does.

Here's a build with those changes:
[Loop.zip](https://github.com/MrKai77/Loop/files/14565803/Loop.zip)

@Soft-Bred *hopefully* this fixes the issue with Notion not working with Loop as well, but I'm not sure since I wasn't able to reproduce the issue on my computer. I would appreciate it if you could test this build with Notion as well :)

**Comment by JaceThings** [comment]
HEHEHEHEH IT WORKS!!!! THATS IT!

Both Firefox & Notion :))))

**Comment by JaceThings** [comment]
Bug... lol. Things break when using previews.

https://github.com/MrKai77/Loop/assets/60551230/20686dcb-93f5-4844-b40d-c68b5a70de7c

**Comment by MrKai77** [comment]
> Things break when using previews.

Do you also have window animations turned on?

**Comment by JaceThings** [comment]
Sorry, I do. Never mind, it's the animation that messes it up. Preview is fine.

**Comment by MrKai77** [comment]
I see... This seems to be an issue with Firefox 😕
Since it works fine on Notion right? Or does Notion also glitch badly when resizing with window animations on?

Anyways, the best solution I can think of would be to auto-disable window animations for apps using that accessibility attribute.

**Comment by JaceThings** [comment]
Notion is the same 😔

I find it funny, when the notion window didn't move properly before this bug was solved, it used to animate very smoothly. Now that it's resolved that animates like shit.


https://github.com/MrKai77/Loop/assets/60551230/7bda1f47-b85b-4e1d-ad5d-553b82e7b84b

**Comment by MrKai77** [comment]
Oh I see :(

I believe this is happening because apps with the `AXEnhancedUserInterface` attribute seem have their own window handling system, which also happens to interfere with Loop when resizing/repositioning windows, in exchange for a smoother window resize animation. 
But when this attribute is disabled by another app (Loop in this case), their custom window animation system is also disabled, so that their window can be fully controlled by a window manager (except for the fact that they still flicker when being animated by Loop).

So I guess the only way to go about this will be to auto-disable window animations from Loop for apps using that use that attribute :(

Anyways, what I find interesting is that Notion on my system doesn't have this accessibility attribute, so Loop's window animations work fine with it. I wonder why that's different between our computers 🤔

**Comment by MrKai77** [comment]
Here's a build with that change:
[Loop.zip](https://github.com/MrKai77/Loop/files/14566205/Loop.zip)

I will probably merge this sometime tomorrow if no other bugs are reported :)
