### ISSUE TITLE
🐞When maximizing the window on the extended screen, it mistakenly moved the window to the primary screen.

### ISSUE THREAD

**Issue by Master-cai** [MrKai77/Loop#292]
### Bug Description

When maximizing the window on the extended screen, it mistakenly moved the window to the primary screen.

### Steps To Reproduce

double click trigger key + direction selection

### Expected Behavior

just maximizing the window on the extended screen

### Actual Behavior

the window is moved the window to the primary screen

### MacOS Version

14.2.1 (23C71)

### Loop Version

Version 1.0.0-beta.14 (644)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Can you try updating to Loop 1.0.0-beta.15 and see if the issue persists?

**Comment by Master-cai** [comment]
@MrKai77 Thanks for your help！I update to beta.14 and everything works fine!

**Comment by Master-cai** [comment]
Sorry to bother you again, i met this issue again. 
I found that when two screens are arranged horizontally, there are no issues, but when the two screens are stacked vertically, this problem occurs. I am currently on the latest version (beta.15).
cc @MrKai77

**Comment by eatmoreduck** [comment]
> Sorry to bother you again, i met this issue again. I found that when two screens are arranged horizontally, there are no issues, but when the two screens are stacked vertically, this problem occurs. I am currently on the latest version (beta.15). cc @MrKai77

me too.  i use 27-inch display as main display and apple built-in display as the secondary display. 27-inch display is on the top and they are arranged vertically.  while  chrome is in the  built-in display and i triggered max chrome , It will become the maximum size of the built-in screen but automatically displays to the 27-inch main display.

**Comment by MrKai77** [comment]
I'm really sorry for the late response but...

I still can't seem to reproduce the problem. Just wondering, but does disabling the preview window from Loop's settings fix the problem?

**Comment by Master-cai** [comment]
@MrKai77 Thanks! when I disable the preview, the bug seems fixed. but i really like the preview, could you fix it in the next update?

**Comment by MrKai77** [comment]
Yes, I will definitely try and fix it! I just wanted to know if a different mechanism to resize the window would work :)

**Comment by iamk3v** [comment]
I think this might be a thing due to the fact that when you move the window to an extended screen, your mouse stays at the old one. I know rectangle has a setting which you can toggle where the mouse follows the window to the extended screen instead of staying where it was. Could be a handy feature, making it faster to navigate aswell since you dont have to move the mouse to the extended screen (probably a reason why you moved it and want to use the mouse there).

**Comment by MrKai77** [comment]
@iamk3v That's a great point! Actually, the next version of Loop will no longer resize windows on the screen with the mouse due to #251.

Here's the latest build, I would appreciate it if you could try it (window snapping is broken in this build) :D
[Loop.zip](https://github.com/MrKai77/Loop/files/15396036/Loop.zip)
