### ISSUE TITLE
🐛 Resize the side bar in vscode after performing loop actions

### ISSUE THREAD

**Issue by frank-miao** [MrKai77/Loop#335]
### Bug Description

When I use vscode, I always make the side bar a bit larger as shown in the below picture

<img width="1512" alt="image" src="https://github.com/MrKai77/Loop/assets/56875483/bb0c8084-9994-47e8-8a11-9ba03a3a7bba">

However after performing a loop action, even maximize the window, the side bar becomes the smallest state as shown below. Meanwhile, the lower panel has also become very small.

<img width="1512" alt="image" src="https://github.com/MrKai77/Loop/assets/56875483/7ddb0703-b386-4f03-a36e-6bdbc823ccfe">

### Steps To Reproduce

1. Open vscode and open its side bar & lower panel
2. Perform one loop action

### Expected Behavior

The side bar and panel remains the same size as before

### Actual Behavior

The side bar and panel become very small

### MacOS Version

14.3

### Loop Version

Version 1.0.0-beta.15 (817)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
Do you have window animations enabled by any chance? If so, can you try again with it disabled?

**Comment by frank-miao** [comment]
> Do you have window animations enabled by any chance? If so, can you try again with it disabled?

Yes, I have enabled this. When it turned off, everything goes fine 👍 . But I think this might still be a small bug.

**Comment by MrKai77** [comment]
Yes, but unfortunately, it is impossible to fix this bug :(

How window animations work is that first, Loop resizes the window to its smallest possible size, then restores the initial size. This is to get a reading on the window's minimum size so that as the window is being animated, it does not get resized off the screen.

If this is removed, many apps with a large minimum size (eg. Xcode) would not work with window animations, as they'd simply resize off the screen, which is obviously not desired.
