### ISSUE TITLE
🐛 Preview window should show new proposed size when centering a window

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#46]
### Bug Description

So there is a bug when switching from maximized to center position

### Steps To Reproduce

1. Go to fullscreen method by clicking right command twice(in my case) + space
2. Try going to center position by clicking right command twice + enter

### Expected Behavior

Should go to center mode with a smaller windows

### Actual Behavior

Doesn't resize and remains as it is

screen recording: https://we.tl/t-2sIOOzxZce

### MacOS Version

Sonoma 14, public beta

### Loop version

1.0.0-beta.10 (351)

**Comment by MrKai77** [comment]
Thanks for the bug report!
Actually, how it happens now is the intended behaviour when centering a window, but the preview window happens to make it look like it should become smaller.
The real bug I should be fixing here is to make the preview window show the new _proposed_ size of the window, rather than showing the a "insetted maximize" shape.

> **Expected Behavior:** Should go to center mode with a smaller windows

If you want to add a bit of padding around the edges of the window to your windows, there's a "Window Padding" setting you can configure in Loop's settings :)

**Comment by MrKai77** [comment]
Here's a fixed build!
[Loop.zip](https://github.com/MrKai77/Loop/files/12775178/Loop.zip)
