### ISSUE TITLE
🐛 Small flicker when animating window resizes

### ISSUE THREAD

**Issue by frieza213** [MrKai77/Loop#48]
### Bug Description

When trying to loop to the opposite side of the current window, i experience some stutter

### Steps To Reproduce

1. Snap your windows to either side of the screen, make sure it is taking up half the screen size
2. Then try the command to snap it to the opposite side and u will experience the bug

### Expected Behavior

It should transition smoothly

### Actual Behavior

Laggy behavior

### MacOS Version

Sonoma 14, public beta

### Loop version

1.0.0-beta.10 (351)

**Comment by frieza213** [comment]
Same with fullscreen and center one now, since i downloaded your previous loop hotfix app @MrKai77

**Comment by MrKai77** [comment]
Thanks for another bug report!
Unfortunately, I am unable to reproduce this bug.
However, I suspect that it may be related to animated window resizing. Are you able to reproduce this bug when that setting is disabled?

**Comment by frieza213** [comment]
yes, please wait for some time

**Comment by frieza213** [comment]
https://we.tl/t-0Amk60ameU here @MrKai77 it doesn't seem much in the recording but i can see it clearly in the real life

**Comment by frieza213** [comment]
@MrKai77 border thickness is the actual reason, when i set it to 0, it returned to the original level of smoothness

**Comment by MrKai77** [comment]
Sorry, but I still don't completely understand the bug :/
Would you mind posting a video comparing the "laggy behavior" when there's a border thickness vs when there isn't a border thickness?
The preview window's border thickness should not be affecting the window resize.

**Comment by frieza213** [comment]
ok

**Comment by frieza213** [comment]
https://gofile.cc/Rb0W/screen-recording-1.mov
https://gofile.cc/qa1y/screen-recording-2.mov

**Comment by frieza213** [comment]
here @MrKai77

**Comment by MrKai77** [comment]
I see... Is this about the little flicker you see when you close Loop? If that's the case, it is not possible to fix :(

How it works is that when you select a direction to Loop, it takes a screenshot of your screen then overlays that on the screen while it resizes the target window to its smallest size, and uses that minimum size to calculate the new window frame, then restores the window to its initial size. Then, it starts animating the window to its target frame. This is the reason why Loop needs screen recording permissions to animate windows. 

Without this screenshot process, you would see an even bigger flicker when you animate window resizes.
In case you'd rather see the code rather than read my explanation (which may have been a little confusing), [here](https://github.com/MrKai77/Loop/blob/0dd98de6229c79253a0631fe46d1d7076532215d/Loop/Window%20Management/Window.swift#L125C10-L125C10) you go :)

Also, just letting you know that you can upload videos directly to Github when sharing them, rather than using a 3rd party provider 😉

**Comment by MrKai77** [comment]
Also, if anyone reading this issue in the future knows a better way to retrieve the minimum size of an `AXUIElement`, please feel free to let me know through an issue, or open a pull request! I'd be more than happy to implement it to improve the smoothness of window resize animations!

**Comment by frieza213** [comment]
> I see... Is this about the little flicker you see when you close Loop? If that's the case, it is not possible to fix :(
> 
> How it works is that when you select a direction to Loop, it takes a screenshot of your screen then overlays that on the screen while it resizes the target window to its smallest size, and uses that minimum size to calculate the new window frame, then restores the window to its initial size. Then, it starts animating the window to its target frame. This is the reason why Loop needs screen recording permissions to animate windows.
> 
> Without this screenshot process, you would see an even bigger flicker when you animate window resizes. In case you'd rather see the code rather than read my explanation (which may have been a little confusing), [here](https://github.com/MrKai77/Loop/blob/0dd98de6229c79253a0631fe46d1d7076532215d/Loop/Window%20Management/Window.swift#L125C10-L125C10) you go :)
> 
> Also, just letting you know that you can upload videos directly to Github when sharing them, rather than using a 3rd party provider 😉

It was too large GitHub has a 10MB limit, mine was around 88MB
