### ISSUE TITLE
🐞 Loop can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by hericius** [MrKai77/Loop#535]
### Bug Description

"Loop" can't be opened because Apple cannot check it for malicious software.

### Steps To Reproduce

Open the newly installed Loop app (download from Git or installed using Brew)

### Expected Behavior

Have an application notarised and signed by Apple.

### Actual Behavior

The application does not appear to have been signed or notarised by Apple

### Screenshots

<img width="273" alt="Screenshot 2024-08-05 at 16 20 09" src="https://github.com/user-attachments/assets/2d811e76-9e0a-418f-9a43-9d621c5956f8">

### macOS Version

macOS 14.5

### Loop Version

Via Brew: 1.1.1

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)
- [ ] I can help with fixing or developing this issue (tick if you can help).

**Comment by SenpaiHunters** [comment]
Run
```sh
xattr -c "/Applications/Loop.app"
```

Loop should be notarised, so I'm very confused again, why there is another issue. All i can think is system security settings, or something.

**Comment by hericius** [comment]
Runs fine with xattr -c 👍

**Comment by SenpaiHunters** [comment]
Yep, `xattr -c` clears the attributes so the app can run. For everyone else who sees this comment: the issue is that Apple has flagged our Apple ID, causing it to fail Gatekeeper verification. We will investigate the cause of this issue in the coming days. In the meantime, to open Loop, you have two options:

1. **Use a shell command in Terminal:** Run the following command:
    ```sh
    xattr -c "/Applications/Loop.app"
    ```

2. **Use the Finder method:** Right-click on the Loop app, select "Open," then right-click on it again and choose "Open." Accept the popup indicating that Apple cannot check for malware.

With this, you should be able to use Loop again. If you encounter any more issues, feel free to ping me or create a new issue. I will keep this issue open for anyone else experiencing the same problem.

**Comment by SenpaiHunters** [comment]
This should now be completely fixed, and there is no need to change Loop or reinstall it for all users, as it's updated live!
