### ISSUE TITLE
✨ [Multiple display support]

### ISSUE THREAD

**Issue by Fierygit** [MrKai77/Loop#543]
### Feature Request Description

if i have two display, hope it can choose my window direction on not selected display;  
move window to another display;

### Final Checks

- [X] My issue is written in English
- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)
- [ ] I can help with the improvement or development of this feature (tick if you can help)

**Comment by MrKai77** [comment]
You can add multi display support to keybinds with these options:
<img width="377" alt="image" src="https://github.com/user-attachments/assets/120752d9-a18a-4416-914d-1e2e798fb790">


Additionally, you may be interested in the "Use screen with cursor" option in the "General" tab, which would use the screen your mouse is currently on, rather than using the current focused screen.
