### ISSUE TITLE
✨ Configuration for animations/transitions

### ISSUE THREAD

**Issue by jacksongoode** [MrKai77/Loop#65]
### Feature Request Description

Beautiful project!

I think it might be nice to have the ability to configure the speed/bounciness and toggle of the preview animations. Sometimes it's a little too much movement on the screen when quickly switching.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Thank you so much!
I too, have thought of this as well. However, the reason I haven't done this yet is that I don't want to make Loop's user interface a bit *too* overwhelming to any user. 
At the moment, Loop's preview window animations are defined by their: `stiffness` and `damping`, but I expect new users (and probably lots of experienced users) will not know how to configure these two settings. How would you envision the user configuring this feature in Loop? Would a slider for duration make sense?
EDIT: fixed a funny typo

**Comment by jacksongoode** [comment]
I think a toggle to disable the transitions between each preview shape would be a good first step. Sometimes I just want to see the final orientation of the shape I'm planning on snapping to, without the animations.

I suppose this could be a duration slider where far left is "0" (animations are off) and far right could be the default transition duration. I can't imagine anyone would want a slower transition :)

**Comment by MrKai77** [comment]
Awesome, got it!
Will try and get this done within the next few days!

**Comment by MrKai77** [comment]
Ok... got this done in much less time than a "few days"!
Here's the latest build (it also contains the feature you wanted in #66): [Loop.zip](https://github.com/MrKai77/Loop/files/13184353/Loop.zip)
You can find the animation setting in the preview window tab in the settings window. I also sped up the default animation duration. How does this look? 
<img width="472" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/27f63662-85fa-49ba-8980-8a0fb2b43fb6">

The only part that bothers me is that no one is likely to animate with a speed below 15-20ms, because at that point, it makes more sense to just have it instantly show the next position. I'm starting to think that this may work better if the user could select a animation duration from a picker (like how they select an icon), which has 3 options: `Instant`, `Fast` and `Smooth`, which then would adjust the animation duration for all of Loop's UI.
So, I'll try doing this and see how it goes!

**Comment by MrKai77** [comment]
Alright, I have implemented it and I'm pretty happy with how it turned out! Here's a screenshot of the setting:
<img width="466" alt="image" src="https://github.com/MrKai77/Loop/assets/68963405/41f5c7ca-1a6a-4538-b4c4-8880185841ad">
EDIT: fixed another funny typo

**Comment by jacksongoode** [comment]
That's beautiful! And yes, sometimes less is more in terms of user configuration and ease! Wonderful job!
