### ISSUE TITLE
🐛 Settings toolbar items maintain active state on lost focus

### ISSUE THREAD

**Issue by Zabriskije** [MrKai77/Loop#80]
### Bug Description

Previously selected menu items remain highlighted until hovered again.

### Steps To Reproduce

1. Open Settings
2. Select a menu item that isn't the current one

### Expected Behavior

The previous menu item should lose highlighting.

### Actual Behavior

The previous menu item remain highlighted.

### Screenshots

![Menu items maintain active state on lost focus](https://github.com/MrKai77/Loop/assets/101254295/a672d5c5-310c-43e6-93bb-1c7b79524c1f)

### MacOS Version

Sonoma 14.0 (23A344)

### Loop Version

1.0.0-beta.11 (465)

### Additional Context

Also tested in `beta.10` and seems to work as expected there.

Hope the title makes sense, I don't know if I'm using the right words :P

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single bug (multiple bugs should be reported individually)

**Comment by MrKai77** [comment]
I can reproduce this as well. This seems to be an issue with the [package I use to make the settings window](https://github.com/sindresorhus/Settings) (which is used ever since `1.0.0-beta.11`). 
They seemed to have fixed it [here](https://github.com/sindresorhus/Settings/pull/113), so hopefully updating the package in Loop should fix it (it's currently on 3.0.3 whereas the latest version is 3.0.5)!

**Comment by MrKai77** [comment]
Setting the version to 3.0.5 seems to have mostly fixed it! But I can still reproduce it around once every 10 times. So I think that moving away from using the `Settings` package and making the settings window myself is the way to go. This should be pretty easy since that's how it was before `1.0.0-beta.11`!

**Comment by MrKai77** [comment]
UPDATE: I noticed that after updating to 3.1.0, this doesn't happen anymore (and if it does, if force-redraws the toolbar to make it inactive again), so this bug is now non-existent!

**Comment by Zabriskije** [comment]
The black line under the toolbar gets dragged over when switching from an item to the other:

![Line](https://github.com/MrKai77/Loop/assets/101254295/e1c0de33-2c1b-48f5-ac6c-a6a6ac583e63)

 Do you want me to open a new issue for this?

**Comment by MrKai77** [comment]
Sure!
