### ISSUE TITLE
✨ Multi-monitor support

### ISSUE THREAD

**Issue by jacksongoode** [MrKai77/Loop#82]
### Feature Request Description

It would be nice to use a modifier along with the existing shortcuts to move a window to a new monitor. The existing orientation of the window could be preserved or it could just be sent to a generic default position in size on the new monitor.

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by MrKai77** [comment]
Good idea! I'm currently prioritizing #75 because Loop's keybind system may change a lot once that is implemented, but after that, I'll see what I can do!

**Comment by JaceThings** [comment]
I want to bump this because I noticed it while trying to move windows across two screens :p

**Comment by jacksongoode** [comment]
Just thinking of an easy way into this, maybe a user can select a second hotkey button that when pressed (while still holding the main hotkey) rotates through the available monitors to loop to.

**Comment by JaceThings** [comment]
I would much rather it perform like Rectangle does, where if you try to push the window in a direction it can not go, it hops to the next logical position on the other monitor.

If I say go right, while my window is on the right, it would then go to the left of my second screen.

**Comment by MrKai77** [comment]
Interesting! I was thinking:
The user can make a keybind (just like any other) to cycle displays, and on top of that, they would be able to press other user-set keybinds to select a window action on *that* display.

> I would much rather it perform like Rectangle does, where if you try to push the window in a direction it can not go, it hops to the next logical position on the other monitor.

This also sounds like a logical thing to do, but I think cycling keybinds might interfere with this (because I'm assuming that you press that keybind again to move onto the next display)?

**Comment by JaceThings** [comment]
> This also sounds like a logical thing to do, but I think cycling keybinds might interfere with this (because I'm assuming that you press that keybind again to move onto the next display)?

Yes, I would anticipate it to function in the following manner:

Let's consider the scenario where `Right` consists of three cycles:

1. 50%
2. 40%
3. 30%

Upon the 4th press, instead of resetting, it would navigate you to the left side of the subsequent display. On the 5th press, it would shift the window to the right of the current display, thereby initiating the cycle anew.

Here are rectangles. Surprisingly, I never noticed that they don't have cycles for left and right, nor top or bottom. But as I said above, I would much prefer this to be a "last item in the cycle" action. That way, I don't have to remember, "Okay, first I need to press X to move screens, then Y to resize."

Till now, I've been working on the current logic: "Have the app selected, move my mouse to the other screen, and activate my command." Sometimes I forget, but I've gotten used to it. Opening Rectangle for the first time in weeks still feels more intuitive.

https://github.com/MrKai77/Loop/assets/60551230/32b69f39-2212-4ea9-8f9c-0327be9c13a7

**Comment by MrKai77** [comment]
> Upon the 4th press, instead of resetting, it would navigate you to the left side of the subsequent display. On the 5th press, it would shift the window to the right of the current display, thereby initiating the cycle anew.

Just making sure that "current display" means the new display that the window is on?

Otherwise, I think both ways (i.e. the Rectangle way and the keybind to move onto the next display way) are quite intuitive, so I'll try and do them both :D

**Comment by JaceThings** [comment]
Yes you would be correct.
